version: '3'

services:
  web:
    image: nginx
    restart: unless-stopped
    network_mode: host
    ports:
      - "5000:5000" # Needs to match NGINX_PORT
    environment:
      NGINX_PORT: 5000 # This env var must be sustituted in config template
    labels:
      traefik.enable: true
      traefik.http.services.archive.loadbalancer.server.port: 5000
      traefik.http.routers.archive.rule: >
        Host(`archive`) ||
        Host(`archive.home.joe.nyland.io`)
    volumes:
      - /containers/archive/templates:/etc/nginx/templates:ro
      - /tank/archive:/var/www/html:ro
