---
services:
  web:
    image: nginx
    container_name: archive
    restart: unless-stopped
    networks:
      proxy:
    labels:
      traefik.enable: true
      traefik.http.routers.archive.rule: Host(`archive`)
    volumes:
      - /containers/archive/templates:/etc/nginx/templates:ro
      - /tank/archive:/var/www/html:ro

networks:
  proxy:
    external: true
