version: '3'

services:
  web_server:
    image: httpd
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.services.archive.loadbalancer.server.port: 80
      traefik.http.routers.archive.rule: >
        Host(`archive`) ||
        Host(`archive.joe.nyland.io`) ||
        Host(`archive.home.joe.nyland.io`)
    volumes:
      - /tank/archive:/usr/local/apache2/htdocs/archive:ro
      # Overrides the default 'hello world' file
      - /dev/null:/usr/local/apache2/htdocs/index.html:ro
